// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "检查服务和依赖的健康状态",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["system"],
                "summary": "健康检查",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/HealthStatus"
                        }
                    }
                }
            }
        },
        "/api/tasks": {
            "get": {
                "description": "返回任务列表，支持缓存",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["tasks"],
                "summary": "获取所有任务",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            },
            "post": {
                "description": "创建新任务",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["tasks"],
                "summary": "创建任务",
                "parameters": [
                    {
                        "description": "Task data",
                        "name": "task",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/CreateTaskRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        },
        "/api/tasks/{id}": {
            "get": {
                "description": "根据 ID 获取任务详情",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["tasks"],
                "summary": "获取单个任务",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Task ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            },
            "put": {
                "description": "更新任务信息",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["tasks"],
                "summary": "更新任务",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Task ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Task data",
                        "name": "task",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/UpdateTaskRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除指定任务",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["tasks"],
                "summary": "删除任务",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Task ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "HealthStatus": {
            "type": "object",
            "properties": {
                "status": { "type": "string" },
                "db": { "type": "string" },
                "redis": { "type": "string" }
            }
        },
        "Response": {
            "type": "object",
            "properties": {
                "code": { "type": "integer" },
                "message": { "type": "string" },
                "data": { "type": "object" }
            }
        },
        "Task": {
            "type": "object",
            "properties": {
                "id": { "type": "integer" },
                "title": { "type": "string" },
                "done": { "type": "boolean" },
                "created_at": { "type": "string" },
                "updated_at": { "type": "string" }
            }
        },
        "CreateTaskRequest": {
            "type": "object",
            "required": ["title"],
            "properties": {
                "title": { "type": "string" },
                "done": { "type": "boolean" }
            }
        },
        "UpdateTaskRequest": {
            "type": "object",
            "required": ["title"],
            "properties": {
                "title": { "type": "string" },
                "done": { "type": "boolean" }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Task API",
	Description:      "企业级任务管理 API，支持 2 级缓存",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
